### ISSUE TITLE
used xsd:date or datetime etc

### ISSUE THREAD

**Issue by renevoorburg** [netwerk-digitaal-erfgoed/cm-implementation-guidelines#8]
In the schema metadata I see
 schema:dateModified	"11-06-2019 14:29:08"

should that be something like 

 schema:dateModified	"2019-06-11T4:29:08"^^xsd:datetime
or similar?

**Comment by ivozandhuis** [comment]
Thanks! Solved with 92bda84e1fd56e41af53e8ea50fc75aac961b6f7
